export enum ErrorCode {
  PACK_NOT_FOUND = 'PACK_NOT_FOUND',
  SCENARIO_NOT_FOUND = 'SCENARIO_NOT_FOUND',
  VERSION_NOT_FOUND = 'VERSION_NOT_FOUND',
  TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND',
  AGENT_NOT_FOUND = 'AGENT_NOT_FOUND',
  INVALID_SCENARIO_REF = 'INVALID_SCENARIO_REF',
  INVALID_PACK_DATA = 'INVALID_PACK_DATA',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  COMPILATION_ERROR = 'COMPILATION_ERROR',
  POLICY_NOT_FOUND = 'POLICY_NOT_FOUND',
  POLICY_REGISTRATION_FAILED = 'POLICY_REGISTRATION_FAILED',
  SESSION_ALREADY_EXISTS = 'SESSION_ALREADY_EXISTS',
  /** Service misconfiguration detected at startup or request time. */
  INVALID_CONFIG = 'INVALID_CONFIG',
  /** Upstream auth-service failure while minting a JWT for an agent spawn (AUTH-2). */
  AUTH_MINT_FAILED = 'AUTH_MINT_FAILED',
  INTERNAL_ERROR = 'INTERNAL_ERROR'
}
